export const authType = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const categoryType = {
  GET_ALL_CATEGORTY_REQUEST: "GET_ALL_CATEGORTY_REQUEST",
  GET_ALL_CATEGORTY_SUCCESS: "GET_ALL_CATEGORTY_SUCCESS",
  GET_ALL_CATEGORTY_FAILURE: "GET_ALL_CATEGORTY_FAILURE",

  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
};

export const productType = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",

  ADD_NEW_PRODUCT_REQUEST: "ADD_NEW_PRODUCT_REQUEST",
  ADD_NEW_PRODUCT_SUCCESS: "ADD_NEW_PRODUCT_SUCCESS",
  ADD_NEW_PRODUCT_FAILURE: "ADD_NEW_PRODUCT_FAILURE",


  
};
